#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3B2D400CE5BBCA60 (m@robenolt.com)
#
Name     : ua-parser
Version  : 0.8.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/b0/02/94ea43fc432fb112fbb62a89855317c41c210fb5239a2ed9b94ecb63024f/ua-parser-0.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/02/94ea43fc432fb112fbb62a89855317c41c210fb5239a2ed9b94ecb63024f/ua-parser-0.8.0.tar.gz
Source99 : https://files.pythonhosted.org/packages/b0/02/94ea43fc432fb112fbb62a89855317c41c210fb5239a2ed9b94ecb63024f/ua-parser-0.8.0.tar.gz.asc
Summary  : Python port of Browserscope's user agent parser
Group    : Development/Tools
License  : Apache-2.0
Requires: ua-parser-python3
Requires: ua-parser-python
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3

%description
uap-python
==========
A python implementation of the UA Parser (https://github.com/ua-parser,
formerly https://github.com/tobie/ua-parser)

%package python
Summary: python components for the ua-parser package.
Group: Default
Requires: ua-parser-python3

%description python
python components for the ua-parser package.


%package python3
Summary: python3 components for the ua-parser package.
Group: Default
Requires: python3-core

%description python3
python3 components for the ua-parser package.


%prep
%setup -q -n ua-parser-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534858722
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
